# set shell

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'

# Rose Pine Config
set -g @rose_pine_variant 'main'
set -g @rose_pine_date_time '%H:%M'
set -g @rose_pine_directory 'on'

set -g @rose_pine_window_status_separator "  "

# Tmux commands:
set -g default-shell /bin/zsh

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


